/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: interfaces@2009-12-06.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _INTERFACES_H_
#define _INTERFACES_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef if__ns
#define if__ns 2010077215
#define if__ns_id "http://acme.com/if"
#define if__ns_uri "http://acme.com/if"
#endif

#define if_transmit 1705430781
#define if_ipv4_address 400734928
#define if_name 1998270519
#define if_v2_foobar 2009206427
#define if_receive 716682309
#define if_alias 159608788
#define if_packets 384560432
#define if_speed 1423237997
#define if_errors 1226221644
#define if_stats 1979611730
#define if_ipv4_mask 1869276480
#define if_Down 1
#define if_txqueuelen 355502792
#define if_macaddr 1547742567
#define if_number 146471600
#define if_mtu 1751455506
#define if_dropped 1815365056
#define if_interface 221572658
#define if_bytes 1113108825
#define if_collisions 71575584
#define if_Up 0
#define if_status 1950810920
#define if__callpointid_if_stats "if-stats"

#ifdef __cplusplus
}
#endif

#endif
