/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: notif.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _NOTIF_H_
#define _NOTIF_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef notif__ns
#define notif__ns 1697608878
#define notif__ns_id "http://router.com/notif"
#define notif__ns_uri "http://router.com/notif"
#endif

#define notif_DOWN 1
#define notif_linkUp 1621884104
#define notif_startUp 838880749
#define notif_UP 0
#define notif_name 1998270519
#define notif_linkProperty 1724773219
#define notif_iface_flags 1407290280
#define notif_LOOPBACK 5
#define notif_address 1266954393
#define notif_mask 1167181041
#define notif_ifName 1636136248
#define notif_linkDown 740290268
#define notif_newlyAdded 1939024431
#define notif_extensions 6037758
#define notif_MULTICAST 4
#define notif_value 864367181
#define notif_flags 1646628167
#define notif_RUNNING 3
#define notif_BROADCAST 2
#define notif_node_id 98319925
#define notif_ip 1643785435
#define notif_extraId 1201642424

#ifdef __cplusplus
}
#endif

#endif
