#!/usr/bin/env bash
set -eu # Abort the script if a command returns with a non-zero exit code or if
        # a variable name is dereferenced when the variable hasn't been set

RED='\033[0;31m'
GREEN='\033[0;32m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color
NONINTERACTIVE=${NONINTERACTIVE-}

printf "\n${GREEN}##### Basic firewall demo\n${NC}"
printf "${PURPLE}##### Reset\n${NC}"
set +e
ncs --stop &> /dev/null
ncs-netsim stop &> /dev/null
set -e
make clean

printf "\n${GREEN}##### Running the Example\n${NC}"
printf "${PURPLE}##### Build the packages\n${NC}"
make all

printf "\n${PURPLE}##### Start the netsim network\n${NC}"
ncs-netsim start

printf "\n${PURPLE}##### Start NSO\n${NC}"
ncs

printf "\n${PURPLE}##### The XML init file containing the device configuration generated by the ncs-netsim tool (See Makefile)\n${NC}"
cat ./ncs-cdb/netsim_devices_init.xml

printf "\n${PURPLE}##### Sync the configuration from the devices\n${NC}"
ncs_cli -n -u admin -C << EOF
devices sync-from
EOF

printf "\n\n${PURPLE}##### Create a device group for the two devices\n${NC}"
ncs_cli -n -u admin -C << EOF
config
devices device-group core-routers device-name [ c0 j0 ]
commit
EOF

printf "\n\n${PURPLE}##### Create a first basic firewall, point out the device-group, and add rules to limit SSH and SHMP access\n${NC}"
ncs_cli -n -u admin -C << EOF
config
services basic-firewall fw1 firewall-device-group core-routers
services basic-firewall fw1 rule 192.168.1.155/32 22 tcp
services basic-firewall fw1 rule 10.1.1.0/24 161 udp
commit dry-run outformat native
commit
EOF

printf "\n\n${PURPLE}##### Review the resulting service and device configuration\n${NC}"
ncs_cli -n -u admin -C << EOF
show running-config services basic-firewall | nomore
show running-config devices device * config | nomore
EOF

printf "\n\n${PURPLE}##### Configure the custom interface property and enable logging for the firewall instances\n${NC}"
ncs_cli -n -u admin -C << EOF
config
services properties basic-firewall firewall-interface c0 interface-name FastEthernet interface-number 1/0
services basic-firewall fw1 rule 10.1.1.0/24 161 udp log
commit dry-run
commit
end
devices device c0 compare-config
EOF

printf "\n\n${GREEN}##### Cleanup\n${NC}"
if [ -z "$NONINTERACTIVE" ]; then
    printf "${RED}##### Press any key to continue or ctrl-c to exit\n${NC}"
    read -n 1 -s -r

    printf "${PURPLE}##### Stop NSO and the netsim devices\n${NC}"
    ncs --stop
    ncs-netsim stop

    printf "\n${PURPLE}##### Reset the example to its original files\n${NC}"
    make clean
fi

printf "\n${GREEN}##### Done!\n${NC}"
